### ISSUE TITLE
Error with HPV41REF.1

### ISSUE THREAD

**Issue by misshie** [KVD-lab/puma#1]
Dear KVD-lab,

I appreciate your large effort to maintain and update PuMA.

I met some trouble with a Docker version of PuMA v1.2.1 . Processing PaVE's HPV41REF.1 occurs the following error:

```
Query does not have E1^E4 or E8^E2

This is the gene information for HPV41REF.1 after making L1 end of Genome:
Traceback (most recent call last):
  File "/app/puma/scripts/run_puma.py", line 138, in <module>
    main()
  File "/app/puma/scripts/run_puma.py", line 130, in main
    puma.run(args)
  File "/app/puma/scripts/puma.py", line 2297, in run
    puma_output(virus,args)
  File "/app/puma/scripts/puma.py", line 2130, in puma_output
    print_genome_info(virus)
  File "/app/puma/scripts/puma.py", line 2037, in print_genome_info
    del virus['known_E1']
KeyError: 'known_E1'
```

I used a multiple-sequence fasta file contains multiple HPV genomes from PaVE. PuMA worked well with genomes between HPV1 to HPV40.

Please could you suggest if you have some workarounds? Please let me know if additional information is necessary.

**Comment by misshie** [comment]
I found that codes of `scripts/puma.py` v1.2.1 on GitHub and Docker Hub  are different.

```
# scripts/puma on Git Hub 
 if "known_E2" in virus:
        del virus["known_E2"]
 if "known_E1" in virus:
        del virus['known_E1']
 if "known_E8" in virus:
        del virus['known_E8']
```

```
# scripts/puma.py on Docker Hub
    del virus["known_E2"]
    del virus['known_E1']
    del virus['known_E8']
 ```

When you have time, please could yous update the code on Docker Hub?

**Comment by KVDlab** [comment]
@misshie I am sorry, I totally missed this request. The code should be updated in the next couple days!
